using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace MatrixTextClient;

public class MatrixEvent
{
    [JsonPropertyName("content")]
    public JsonElement? Content { get; set; }
    [JsonPropertyName("type")]
    public required string Type { get; set; }
    [JsonPropertyName("sender")]
    public string? Sender { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProps { get; set; }
}

public class ClientEventWithoutRoomID
{
    [JsonPropertyName("content")]
    public JsonElement? Content { get; set; }

    [JsonPropertyName("type")]
    public required string Type { get; set; }

    [JsonPropertyName("sender")]
    public required string Sender { get; set; }

    [JsonPropertyName("event_id")]
    public required string EventId { get; set; }

    [JsonPropertyName("origin_server_ts")]
    public required long OriginServerTs { get; set; }

    [JsonPropertyName("state_key")]
    public string? StateKey { get; set; }

    [JsonPropertyName("unsigned")]
    public UnsignedData? Unsigned { get; set; }

    [JsonExtensionData]
    public Dictionary<string, JsonElement>? AdditionalProps { get; set; }
}

/// <summary>
/// m.presence event
/// </summary>
public class MatrixPresenceEvent
{
    [JsonPropertyName("avatar_url")]
    public string? AvatarUrl { get; set; }

    [JsonPropertyName("currently_active")]
    public bool? CurrentlyActive { get; set; }

    [JsonPropertyName("displayname")]
    public string? DisplayName { get; set; }

    /// <summary>
    /// The last time since this used performed some action, in milliseconds.
    /// </summary>
    [JsonPropertyName("last_active_ago")]
    public long? LastActiveAgo { get; set; }

    [JsonPropertyName("presence")]
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public required Presence Presence { get; set; }

    [JsonPropertyName("status_msg")]
    public string? StatusMessage { get; set; }
}
public enum Presence
{
    [JsonPropertyName("offline")]
    Offline,
    [JsonPropertyName("online")]
    Online,
    [JsonPropertyName("unavailable")]
    Unavailable
}

public class UnsignedData
{
    /// <summary>
    /// The time in milliseconds that has elapsed since the event was sent.
    /// This field is generated by the local homeserver, and may be incorrect
    /// if the local time on at least one of the two servers is out of sync,
    /// which can cause the age to either be negative or greater than it actually is.
    /// </summary>
    [JsonPropertyName("age")]
    public required long Age { get; set; }

    /// <summary>
    /// The room membership of the user making the request, at the time of the event.
    /// </summary>
    [JsonPropertyName("membership")]
    public string? Membership { get; set; }

    /// <summary>
    /// The previous content for this event. This field is generated by the local homeserver,
    /// and is only returned if the event is a state event, and the client has permission to see the previous content.
    /// </summary>
    [JsonPropertyName("prev_content")]
    public JsonElement? PrevContent { get; set; }

    /// <summary>
    /// The event that redacted this event, if any.
    /// </summary>
    [JsonPropertyName("redacted_because")]
    public JsonElement? RedactedBecause { get; set; }

    /// <summary>
    /// The client-supplied transaction ID, for example,
    /// provided via PUT /_matrix/client/v3/rooms/{roomId}/send/{eventType}/{txnId},
    /// if the client being given the event is the same one which sent it.
    /// </summary>
    [JsonPropertyName("transaction_id")]
    public string? TransactionId { get; set; }
}

/// <summary>
/// A stripped down state event
/// </summary>
/// <remarks>
/// Clients should only use stripped state events when they don’t have access to the proper
/// state of the room. Once the state of the room is available, all stripped state should be discarded.
/// </remarks>
public class StrippedStateEvent
{
    [JsonPropertyName("content")]
    public JsonElement? Content { get; set; }

    [JsonPropertyName("sender")]
    public required string Sender { get; set; }

    [JsonPropertyName("state_key")]
    public string? StateKey { get; set; }

    [JsonPropertyName("type")]
    public required string Type { get; set; }
}
